services:
  invoker:
    build:
      context: .
      dockerfile: invoker/Dockerfile
    ports:
      - 65500-65535:80
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"